name: Build Cobalt for Xbox (UWP XAPP)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Abhängigkeiten installieren
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-python
            mingw-w64-x86_64-nodejs
            mingw-w64-x86_64-toolchain

      - name: Virtuelle Python-Umgebung einrichten
        shell: bash
        run: |
          python -m venv ~/.virtualenvs/cobalt_dev
          source ~/.virtualenvs/cobalt_dev/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cobalt für Xbox konfigurieren
        shell: bash
        run: python cobalt/build/gn.py -c devel -p xb1

      - name: Cobalt für Xbox bauen
        shell: bash
        run: ninja -C out/xb1_devel cobalt_install

      - name: UWP XAPP erstellen
        shell: bash
        run: python starboard/xb1/tools/packager.py -s out/xb1_devel/ -o out/xb1_devel/package -p cobalt

      - name: Build-Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: Cobalt-Xbox-UWP-XAPP
          path: out/xb1_devel/package/*.appx
          retention-days: 7
